// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: qst.proto

package qst_comm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qst_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_qst_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_qst_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type ExecHint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idx  uint32  `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"` //use idx avoid string convert
	Args *string `protobuf:"bytes,2,opt,name=args,proto3,oneof" json:"args,omitempty"`
}

func (x *ExecHint) Reset() {
	*x = ExecHint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qst_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecHint) ProtoMessage() {}

func (x *ExecHint) ProtoReflect() protoreflect.Message {
	mi := &file_qst_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecHint.ProtoReflect.Descriptor instead.
func (*ExecHint) Descriptor() ([]byte, []int) {
	return file_qst_proto_rawDescGZIP(), []int{1}
}

func (x *ExecHint) GetIdx() uint32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *ExecHint) GetArgs() string {
	if x != nil && x.Args != nil {
		return *x.Args
	}
	return ""
}

type Display struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Icon    *string `protobuf:"bytes,2,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	ArgHint *string `protobuf:"bytes,3,opt,name=argHint,proto3,oneof" json:"argHint,omitempty"`
}

func (x *Display) Reset() {
	*x = Display{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qst_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Display) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Display) ProtoMessage() {}

func (x *Display) ProtoReflect() protoreflect.Message {
	mi := &file_qst_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Display.ProtoReflect.Descriptor instead.
func (*Display) Descriptor() ([]byte, []int) {
	return file_qst_proto_rawDescGZIP(), []int{2}
}

func (x *Display) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Display) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *Display) GetArgHint() string {
	if x != nil && x.ArgHint != nil {
		return *x.ArgHint
	}
	return ""
}

type DisplayList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Display `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *DisplayList) Reset() {
	*x = DisplayList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qst_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisplayList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayList) ProtoMessage() {}

func (x *DisplayList) ProtoReflect() protoreflect.Message {
	mi := &file_qst_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayList.ProtoReflect.Descriptor instead.
func (*DisplayList) Descriptor() ([]byte, []int) {
	return file_qst_proto_rawDescGZIP(), []int{3}
}

func (x *DisplayList) GetList() []*Display {
	if x != nil {
		return x.List
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qst_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_qst_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_qst_proto_rawDescGZIP(), []int{4}
}

var File_qst_proto protoreflect.FileDescriptor

var file_qst_proto_rawDesc = []byte{
	0x0a, 0x09, 0x71, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x71, 0x73, 0x74,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x22, 0x19, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72,
	0x22, 0x3e, 0x0a, 0x08, 0x45, 0x78, 0x65, 0x63, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x69, 0x64, 0x78, 0x12, 0x17,
	0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x61, 0x72, 0x67, 0x73,
	0x22, 0x6a, 0x0a, 0x07, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x17, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x04, 0x69, 0x63, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x61, 0x72, 0x67, 0x48,
	0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x61, 0x72, 0x67,
	0x48, 0x69, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x69, 0x63, 0x6f, 0x6e,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x61, 0x72, 0x67, 0x48, 0x69, 0x6e, 0x74, 0x22, 0x34, 0x0a, 0x0b,
	0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x71, 0x73, 0x74, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x70, 0x0a, 0x08, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x12, 0x33, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x70, 0x70, 0x12, 0x0f, 0x2e, 0x71, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x1a, 0x15, 0x2e, 0x71, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x44,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x06,
	0x52, 0x75, 0x6e, 0x41, 0x70, 0x70, 0x12, 0x12, 0x2e, 0x71, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6d,
	0x6d, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x48, 0x69, 0x6e, 0x74, 0x1a, 0x0f, 0x2e, 0x71, 0x73, 0x74,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x0f, 0x5a,
	0x0d, 0x6b, 0x6d, 0x64, 0x72, 0x2f, 0x71, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qst_proto_rawDescOnce sync.Once
	file_qst_proto_rawDescData = file_qst_proto_rawDesc
)

func file_qst_proto_rawDescGZIP() []byte {
	file_qst_proto_rawDescOnce.Do(func() {
		file_qst_proto_rawDescData = protoimpl.X.CompressGZIP(file_qst_proto_rawDescData)
	})
	return file_qst_proto_rawDescData
}

var file_qst_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_qst_proto_goTypes = []interface{}{
	(*Input)(nil),       // 0: qst_comm.Input
	(*ExecHint)(nil),    // 1: qst_comm.ExecHint
	(*Display)(nil),     // 2: qst_comm.Display
	(*DisplayList)(nil), // 3: qst_comm.DisplayList
	(*Empty)(nil),       // 4: qst_comm.Empty
}
var file_qst_proto_depIdxs = []int32{
	2, // 0: qst_comm.DisplayList.list:type_name -> qst_comm.Display
	0, // 1: qst_comm.Interact.ListApp:input_type -> qst_comm.Input
	1, // 2: qst_comm.Interact.RunApp:input_type -> qst_comm.ExecHint
	3, // 3: qst_comm.Interact.ListApp:output_type -> qst_comm.DisplayList
	4, // 4: qst_comm.Interact.RunApp:output_type -> qst_comm.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_qst_proto_init() }
func file_qst_proto_init() {
	if File_qst_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qst_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qst_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecHint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qst_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Display); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qst_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisplayList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qst_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_qst_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_qst_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qst_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qst_proto_goTypes,
		DependencyIndexes: file_qst_proto_depIdxs,
		MessageInfos:      file_qst_proto_msgTypes,
	}.Build()
	File_qst_proto = out.File
	file_qst_proto_rawDesc = nil
	file_qst_proto_goTypes = nil
	file_qst_proto_depIdxs = nil
}
